### ISSUE TITLE
Question: badgeview on UIBarButtonItem

### ISSUE THREAD

**Issue by BrettyWhite** [JaviSoto/JSBadgeView#22]
Hello I have been looking at this for some time now and haven't quite found a solution. I am looking to put a badge view on a Bar Button Item and am getting the warning (it force closes) "Incompatible pointer types sending 'UIBarButtonItem *' to parameter of type 'UIView *'" 

I was hoping someone with more experience than I has either dealt with this prior or has found a solution. 

Many thanks for your time!

**Comment by liuxuan30** [comment]
Check out barButtonItem's property customView. I use this property to add a Button inside the customView and get the JSBadgeView works fine.
