### ISSUE TITLE
New Cocoapods version

### ISSUE THREAD

**Issue by sticksen** [JaviSoto/JSBadgeView#38]
Referring to #35 

Hey Javi,
thanks for the new Tag, but in order to get it up to the cocoapods repo, it has to be pushed in the Specs repository. From what I can see, this didn´t happen yet:
https://github.com/CocoaPods/Specs/tree/4a2a7d017cddfdec782da5bbdd2abee353549280/Specs/JSBadgeView

Cheers,
Marc

**Comment by bestwnh** [comment]
Hope it can be done. @JaviSoto Please, Just one step. `pod trunk push`

**Comment by JaviSoto** [comment]
Sorry about that! I think I just did it. Let me know if I missed anything (I'm kind of a Cocoapods noob haha)
