### ISSUE TITLE
Add badgeSize method to public API

### ISSUE THREAD

**Issue by pblondin** [JaviSoto/JSBadgeView#43]
The following properties should be exposed to public API and be customizable using Appeareance.

JSBadgeViewShadowRadius 
JSBadgeViewHeight
JSBadgeViewTextSideMargin
JSBadgeViewCornerRadius

I will be happy to do a pull request when I have more time.

Regards,

**Comment by JaviSoto** [comment]
I would definitely welcome pull requests :)

**Comment by pblondin** [comment]
FYI, I had to fork this project and hardcode proper values to fit my needs for current project. Too busy right do, but I'll do when I can :)

**Comment by JaviSoto** [comment]
I understand :) That's totally fine! I hope my code at least saved you some time :) I understand that the way `JSBadgeView` looks, and the customizations available may not be enough for everybody. But I'm happy to make it better :)
