### ISSUE TITLE
Project Structure

### ISSUE THREAD

**Issue by seanoshea** [JaviSoto/JSBadgeView#45]
Hi there,

Was wondering whether you'd be open to restructuring the repo for this library to be more along the lines of a `pod lib create JSBadgeView` ala https://guides.cocoapods.org/making/using-pod-lib-create.html? I just included this repo in a pull request for a feature at work and it was pointed out that importing the pod means that the same project appeared in the project too. I believe using `pod lib create JSBadgeView` wouldn't result in the sample project appearing.

I'd be happy to contribute to this in much the same manner as https://github.com/AFNetworking/AFAmazonS3Manager/pull/88 if you'd be open to the restructuring of the library.

Cheers,

Sean

**Comment by JaviSoto** [comment]
I'd happily accept a pull request with this :) I have currently no free time to dedicate to this project, so I would love all help!

**Comment by seanoshea** [comment]
OK - will take a look at it & see what I can cook up @JaviSoto

**Comment by seanoshea** [comment]
See https://github.com/JaviSoto/JSBadgeView/pull/46 for details.

**Comment by JaviSoto** [comment]
Fixed :)
