### ISSUE TITLE
Badge does not show on simulator iOS 7.1

### ISSUE THREAD

**Issue by meitneshi** [JaviSoto/JSBadgeView#49]
Hello,

I use your library to add some badge over button in my app. When I run it on device or simulator on iOS8.3 it works, I see the badge but when I put the app on the simulator with device on iOS7.1, the badge does not show itself.
Did I miss something about the compatibility of your library ?

**Comment by vikysaran** [comment]
I think you set `clipSubview = YES;` for the parent view of this badge. By default appears out of the frame and if this property is `YES` then badge will get cutoff.
