### ISSUE TITLE
badge is clipped.

### ISSUE THREAD

**Issue by tounaobun** [JaviSoto/JSBadgeView#50]
JSBadgeView's parent view is UIImageView,and it's property masksToBounds is set to YES.The top right badgeText is clipped.How to resolve this issue?

**Comment by JaviSoto** [comment]
Instead of making the parent view be the UIImage view, make them siblings, both children of the same UIView. Let me know if that works.

**Comment by tounaobun** [comment]
It works as I make two of them siblings.Thanks.I'll close the issue.
