### ISSUE TITLE
Badge does not appear unless I tap on barButtonItem

### ISSUE THREAD

**Issue by joelbanzatto** [JaviSoto/JSBadgeView#52]
Hello,

I have a QRCode Scanner.. when I scan the code and tap on 'add button' I set the badge of my BarButtonItem, see:

`JSBadgeView *badgeView = [[JSBadgeView alloc] initWithParentView:self.productsButtonItem alignment:JSBadgeViewAlignmentTopRight];`
`badgeView.badgeText = @"3";`

But the badge does not apper unless I tap on my barButtonItem..

I have to do something more?

Thanks

**Comment by JaviSoto** [comment]
Can I see the code around it?
