### ISSUE TITLE
Build error in Xcode 7.3 using JSBadgeView from CocoaPods

### ISSUE THREAD

**Issue by SixFiveSoftware** [JaviSoto/JSBadgeView#57]
Hi, I'm getting an odd build error when adding JSBadgeView via CocoaPods. I thought it might be a config issue with my project, so I created a brand new project and nothing else but installed JSBadgeView via CocoaPods and still same issue. If ye GitHub gods favor me today, the screenshot of my error might be attached here :-). I have not seen this with any other pod I've added. Any ideas? Thanks!
<img width="869" alt="screen shot 2016-04-01 at 2 25 41 pm" src="https://cloud.githubusercontent.com/assets/2272819/14216285/f5d21c12-f815-11e5-970e-efa2d6fca0a9.png">

**Comment by SixFiveSoftware** [comment]
I did notice that the .bundle file is actually located one folder down, so instead of "..../Debug-iphonesimulator/JSBadgeView/" it's in "..../Debug-iphonesimulator/JSBadgeView/JSBadgeView/". Searching around, I tried adding it to my project and explicitly adding a ref to it in the project's General tab's settings, but to no avail.

**Comment by JaviSoto** [comment]
Hmmm that's strange, because this project doesn't have any resource bundle. I wonder if it's because of "resource_bundles" in the podspec: https://github.com/JaviSoto/JSBadgeView/blob/master/JSBadgeView.podspec

Maybe we can get rid of that?

**Comment by SixFiveSoftware** [comment]
Not sure...perhaps? There isn't anything in that Pod/Assets folder, so maybe? I worked around it by adding the .h/.m files directly to my project and it worked fine.

**Comment by gabornagyfarkas** [comment]
@JaviSoto @SixFiveSoftware Hi there! We're facing the same issue with CP 1.0.1, the problem is indeed that line. Could you please remove it from the spec? The CP [documentation](https://guides.cocoapods.org/syntax/podspec.html#resources) says:

> resources multi-platform
> 
> A list of resources that should be copied into the target bundle.
> 
> We strongly recommend library developers to adopt resource bundles as there can be name collisions using the resources attribute. Moreover, resources specified with this attribute are copied directly to the client target and therefore they are not optimised by Xcode.

But since you're not using any resources it could be omitted.

**Comment by JaviSoto** [comment]
Fixed
