### ISSUE TITLE
Drawing in legacy mode on iOS 12

### ISSUE THREAD

**Issue by alexandre-g** [JaviSoto/JSBadgeView#63]
`isUIKitFlatMode = (NSVersionOfLinkTimeLibrary("UIKit") >> 16) >= UIKitVersionNumber_iOS_7_0;`
returns false

**Comment by yanzhiwei147** [comment]
This PR merged now, so we trunk version 2.0.0 to cocoapods specs now?

**Comment by JaviSoto** [comment]
Done! Sorry about that.

**Comment by yanzhiwei147** [comment]
Good! Thank you very much.
